name: Codequality

on: workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - run: npm ci --no-fund --no-audit
      - run: npm run lint
      - run: npm run codestyle
