name: Release

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

on:
  push:
    branches:
      - "main"

jobs:
  codequality:
    uses: ./.github/workflows/codequality.yml

  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release:
    needs: [codequality, test]
    runs-on: ubuntu-latest
    steps:
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: 0

  coverage:
    needs: [release]
    uses: ./.github/workflows/coverage.yml
    secrets: inherit
